# Generated by Django 5.2 on 2025-06-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILGHT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_type',
            field=models.CharField(default='Boeing 737', max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_distance', models.FloatField()),
                ('total_duration', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('total_fuel_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='FILGHT.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origins', to='FILGHT.airport')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField()),
                ('layover_duration', models.FloatField(default=0.0)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FILGHT.airport')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FILGHT.route')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='FILGHT.RouteStop', to='FILGHT.airport'),
        ),
    ]
