# Generated by Django 5.2 on 2025-06-21 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILGHT', '0002_flight_aircraft_type_flight_fuel_cost_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='FL001', max_length=20),
        ),
        migrations.AddField(
            model_name='routestop',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='layover_duration',
            field=models.FloatField(default=1.5),
        ),
    ]
