# Generated by Django 5.2 on 2025-06-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILGHT', '0003_airport_timezone_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time']},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='cost',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='Generic Airlines', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
