# Generated by Django 5.2.4 on 2025-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FILGHT", "0005_fuelefficiency_operationalconstraint_safetyfactor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="airport",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
