# Generated by Django 5.2.4 on 2025-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FILGHT", "0006_airport_city_airport_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
