# Generated by Django 5.2.4 on 2025-07-24 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILGHT', '0007_airport_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='fuel_efficiency',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='fuel_efficiency',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='safety_factors',
        ),
        migrations.RemoveField(
            model_name='route',
            name='safety_factors',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_waypoints',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_waypoints',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='weather_conditions',
        ),
        migrations.RemoveField(
            model_name='route',
            name='weather_conditions',
        ),
        migrations.RenameField(
            model_name='operationalconstraint',
            old_name='description',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='operationalconstraint',
            old_name='location_lat',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='altitude_penalties',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='congestion_zones',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='delay_penalties',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='operational_constraints',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='optimization_complexity',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='waypoint_count',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='weather_data_points',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='active',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='altitude_max',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='altitude_min',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='impact_score',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='location_lon',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='operationalconstraint',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='operational_constraints',
        ),
        migrations.RemoveField(
            model_name='route',
            name='optimization_complexity',
        ),
        migrations.RemoveField(
            model_name='route',
            name='waypoint_count',
        ),
        migrations.RemoveField(
            model_name='route',
            name='weather_data_points',
        ),
        migrations.AddField(
            model_name='operationalconstraint',
            name='unit',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='operationalconstraint',
            name='constraint_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='operationalconstraint',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FILGHT.aircraftprofile'),
        ),
        migrations.DeleteModel(
            name='FuelEfficiency',
        ),
        migrations.DeleteModel(
            name='SafetyFactor',
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
        migrations.DeleteModel(
            name='WeatherCondition',
        ),
    ]
